In [54]:
# Pandas Practice Problems

In [55]:
%load_ext pycodestyle_magic
%flake8_on --ignore E266 --max_line_length 99
%reload_ext pycodestyle_magic

The pycodestyle_magic extension is already loaded. To reload it, use:
  %reload_ext pycodestyle_magic

In [56]:
from urllib import request
from os import path
import pandas as pd
import numpy as np

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/forest-fires/"
fn = "forestfires.csv"
if not path.exists(fn):
    data = request.urlopen(url + fn).read()
    with open(fn, 'wb') as fhand:
        fhand.write(data)

ff = pd.read_csv("forestfires.csv")
ff

# print(ff.info())

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

### Problem 1: Filtering and computing a mean
Write a function that returns the average rainfall on days with wind speed above 6 mph.

In [57]:
def windy_rain():
    above_6 = ff[ff["wind"] > 6]
    return above_6["rain"].mean()

In [58]:
assert abs(windy_rain() - 0.0412698) < 1e-6

### Problem 2: Filtering and computing a sum
Write a function that take a month as an argument and returns the total rainfall during the month.

In [59]:
def monthly_rain(mon):
    month_df = ff[ff["month"] == mon]
    return month_df["rain"].sum()

In [60]:
assert abs(monthly_rain("aug") - 10.8) < 1e-6
assert abs(monthly_rain("mar") - 0.2) < 1e-6

In [67]:
#above_6 = ff[ff["wind"] > 6]
#above_6.mean(numeric_only=True)["rain"]
%reload_ext pycodestyle_magic

### Problem 3: Loading Pandas data frames
Download the white wine dataset from [https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv](https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv), and load it into a Pandas dataframe called `df`.

In [68]:
from urllib import request
from os import path
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/"
fn = "winequality-white.csv"
df = pd.read_csv(fn, sep = ";")
%reload_ext pycodestyle_magic

In [63]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [64]:
assert abs(df["citric acid"].mean() - 0.3341915) < 1e-8

### Problem 4: pipe
Write a function that takes a user-defined function as an argument.
It uses `pipe` to apply the function to each wine pH, and returns the mean of the values returned by the user-defined function.

In [77]:
def mean_ph(user_fun):
    return df.pipe(user_fun)["pH"].mean()

In [78]:
mean_ph(lambda x: x**2)

np.float64(10.187840690077584)

In [79]:
assert abs(mean_ph(lambda x: x**2) - (df.pH ** 2).mean()) < 1e-8